language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  fast_finish: true

install:
  - travis_retry composer update $COMPOSER_OPTS --prefer-dist
  - if [ "$COMPOSER_OPTS" == "--prefer-lowest" ]; then composer require guzzlehttp/ringphp:1.0.7 --prefer-dist; fi
  - if [ "$COMPOSER_OPTS" == "--prefer-lowest" ]; then composer require guzzlehttp/guzzle:5.3.1 --prefer-dist; fi

script:
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ] || [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then bin/phpunit --coverage-text --coverage-clover coverage.xml; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi

notifications:
  email: false
